### ISSUE TITLE
No authorized requests

### ISSUE THREAD

**Issue by omalave** [ChatCamp/ChatCamp-JavaScript-Examples#6]
Hi, I'm trying to test ChatCamp but it show me this errors and I have appId and channelId correct

![image](https://user-images.githubusercontent.com/3420419/69891006-4db94200-12c7-11ea-8ea4-18d3c86464b5.png)

Any clue?

**Comment by katendeglory** [comment]
Same issue here.

I believe this might be an overall bug with the entire tool.

The javascript examples from their demo page aren't working as well. Click on any demo in the link below. 

https://chatcamp.io/demo

**Comment by darklrd** [comment]
The error you're encountering typically occurs when there's a problem with the authentication process, specifically with the `access_token` which is a crucial part of user creation and authentication in ChatCamp.

To create a user, you should make a POST request to `/api/2.0/users.create` with the necessary payload. Here is an example of the payload:

```
{
  "id": "the_user_id",
  "display_name": "User's Display Name",
  "first_name": "User's First Name",
  "last_name": "User's Last Name",
  "email": "user@email.com",
  "phone_number": "User's Phone Number",
  "profile_url": "URL of the User's Profile",
  "avatar_url": "URL of the User's Avatar",
  "access_token": "User's Access Token"
}
```

After creating a user and obtaining the access_token, you need to initialize the ChatCamp SDK with the appId and then authenticate the user session with the access_token as described in our [JavaScript Chat Authentication Documentation](https://docs.chatcamp.io/docs/javascript-chat-authentication).

Please ensure that you follow the steps outlined in the documentation carefully. If authentication is not desired for testing purposes, we can disable the `access_token` requirement for your account. Keep in mind this should only be considered if you have adequate security measures in place.

We've checked our demo pages, and they are functioning as expected. If the issue persists, please double-check your `app_id` and ensure that the `access_token` is being used correctly as per the documentation.

For any further assistance, feel free to reach out to our support team.
